// data/sampleFlashcards.ts

export interface NursingCategory {
  name: string;
  subcategories: string[];
}

export const nursingCategories: NursingCategory[] = [
  {
    name: "Fundamentals of Nursing",
    subcategories: [
      "Basic Concepts & Skills",
      "Health Assessment",
      "Nursing Process",
      "Patient Safety",
      "Infection Control",
      "Vital Signs",
      "Medication Administration",
      "Documentation",
    ],
  },
  {
    name: "Medical Surgical Nursing",
    subcategories: [
      "Cardiovascular Disorders",
      "Respiratory Disorders",
      "Gastrointestinal Disorders",
      "Endocrine Disorders",
      "Neurological Disorders",
      "Musculoskeletal Disorders",
      "Renal & Urinary Disorders",
      "Oncology",
      "Perioperative Care",
    ],
  },
  {
    name: "Maternal Newborn Nursing",
    subcategories: [
      "Antepartum Care",
      "Intrapartum Care",
      "Postpartum Care",
      "Newborn Care",
      "High-Risk Pregnancy",
      "Labor & Delivery Complications",
    ],
  },
  {
    name: "Pediatric Nursing",
    subcategories: [
      "Growth & Development",
      "Pediatric Assessment",
      "Common Childhood Illnesses",
      "Congenital Disorders",
      "Pediatric Emergencies",
      "Childhood Immunizations",
    ],
  },
  {
    name: "Mental Health Nursing",
    subcategories: [
      "Therapeutic Communication",
      "Mood Disorders",
      "Anxiety Disorders",
      "Schizophrenia & Psychotic Disorders",
      "Personality Disorders",
      "Substance Use Disorders",
      "Crisis Intervention",
    ],
  },
  {
    name: "Pharmacology",
    subcategories: [
      "Drug Classifications",
      "Medication Safety",
      "Adverse Effects & Interactions",
      "Dosage Calculations",
      "Cardiovascular Medications",
      "Antimicrobials",
      "Pain Management",
      "Endocrine Medications",
    ],
  },
  {
    name: "Critical Care Nursing",
    subcategories: [
      "Hemodynamic Monitoring",
      "Mechanical Ventilation",
      "Shock States",
      "Sepsis & Septic Shock",
      "ACLS Protocols",
      "Trauma Care",
    ],
  },
  {
    name: "Community Health Nursing",
    subcategories: [
      "Epidemiology",
      "Health Promotion",
      "Communicable Diseases",
      "Environmental Health",
      "Home Health Care",
      "Disaster Preparedness",
    ],
  },
  {
    name: "Nursing Leadership and Management",
    subcategories: [
      "Delegation & Prioritization",
      "Quality Improvement",
      "Ethical & Legal Issues",
      "Staff Development",
      "Conflict Resolution",
    ],
  },
  {
    name: "Gerontological Nursing",
    subcategories: [
      "Aging Process",
      "Elder Abuse",
      "Dementia & Alzheimer's",
      "Polypharmacy",
      "Fall Prevention",
      "End-of-Life Care",
    ],
  },
  {
    name: "ECG Interpretation",
    subcategories: [
      "Basic ECG Waves & Intervals",
      "Arrhythmias",
      "Myocardial Infarction Patterns",
      "Heart Blocks",
      "Pacemaker Rhythms",
    ],
  },
  {
    name: "Dosage Calculations",
    subcategories: [
      "Metric Conversions",
      "IV Flow Rates",
      "Pediatric Dosage",
      "Reconstitution",
      "Insulin Calculations",
    ],
  },
  {
    name: "Nursing Assessment",
    subcategories: [
      "Head-to-Toe Assessment",
      "Pain Assessment",
      "Neurological Assessment",
      "Cardiovascular Assessment",
      "Respiratory Assessment",
    ],
  },
  {
    name: "Clinical Skills",
    subcategories: [
      "Wound Care",
      "Catheterization",
      "NG Tube Insertion",
      "Tracheostomy Care",
      "IV Therapy",
      "Blood Transfusion",
    ],
  },
];

// Sample flashcards (just 10–15 examples — you can add hundreds more)
export const sampleFlashcards = [
  {
    id: "sample-1",
    question: "What is the normal range for adult respiratory rate?",
    answer: "12–20 breaths per minute",
    category: "Fundamentals of Nursing",
    subcategory: "Vital Signs",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-2",
    question: "Which isolation precaution is used for tuberculosis?",
    answer: "Airborne precautions",
    category: "Fundamentals of Nursing",
    subcategory: "Infection Control",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-3",
    question: "What is the first step in the nursing process?",
    answer: "Assessment",
    category: "Fundamentals of Nursing",
    subcategory: "Nursing Process",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-4",
    question: "A patient with CHF is prescribed furosemide. What electrolyte imbalance should the nurse monitor for?",
    answer: "Hypokalemia",
    category: "Medical Surgical Nursing",
    subcategory: "Cardiovascular Disorders",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-5",
    question: "What is the priority nursing action for a patient experiencing anaphylaxis?",
    answer: "Administer epinephrine",
    category: "Critical Care Nursing",
    subcategory: "Shock States",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-6",
    question: "At what gestational age does quickening typically occur in a primigravida?",
    answer: "18–20 weeks",
    category: "Maternal Newborn Nursing",
    subcategory: "Antepartum Care",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-7",
    question: "A 2-year-old child is in which Piaget developmental stage?",
    answer: "Preoperational stage",
    category: "Pediatric Nursing",
    subcategory: "Growth & Development",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-8",
    question: "What is the therapeutic range for serum lithium?",
    answer: "0.6–1.2 mEq/L",
    category: "Mental Health Nursing",
    subcategory: "Mood Disorders",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-9",
    question: "Which insulin should be given before meals?",
    answer: "Rapid-acting (e.g., lispro, aspart)",
    category: "Pharmacology",
    subcategory: "Endocrine Medications",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-10",
    question: "What is the most common cause of acute kidney injury in hospitalized patients?",
    answer: "Prerenal azotemia (hypoperfusion)",
    category: "Medical Surgical Nursing",
    subcategory: "Renal & Urinary Disorders",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-11",
    question: "How many seconds should hands be rubbed together during routine handwashing?",
    answer: "At least 20 seconds",
    category: "Fundamentals of Nursing",
    subcategory: "Infection Control",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
  {
    id: "sample-12",
    question: "What is the antidote for heparin overdose?",
    answer: "Protamine sulfate",
    category: "Pharmacology",
    subcategory: "Medication Safety",
    timesReviewed: 0,
    correctCount: 0,
    customCard: false,
  },
];

export default {
  nursingCategories,
  sampleFlashcards,
};