export const userData: User[] = [
    {
        key: '1',
        serialId: '#01',
        userName: 'Omar Yusuf',
        email: 'omar@gmail.com',
        contactNumber: '(406) 555-0120',
        subscription: 'Monthly',
        country: 'Bangladesh',
        profession: 'Software Engineer',
        status: 'active',
    },
    {
        key: '2',
        serialId: '#02',
        userName: 'Nikolai Ivanovich',
        email: 'nikolai@gmail.com',
        contactNumber: '(603) 555-0123',
        subscription: 'Yearly',
        country: 'Russia',
        profession: 'Designer',
        status: 'delete',
    },
    {
        key: '3',
        serialId: '#03',
        userName: 'Brooklyn Simmons',
        email: 'brooklyn@gmail.com',
        contactNumber: '(316) 555-0116',
        subscription: 'Monthly',
        country: 'USA',
        profession: 'Product Manager',
        status: 'active',
    },
    {
        key: '4',
        serialId: '#04',
        userName: 'Brooklyn Simmons',
        email: 'brooklyn@gmail.com',
        contactNumber: '(316) 555-0116',
        subscription: 'Monthly',
        status: 'active',
        country: 'Bangladesh',
        profession: 'Product Manager',
    },
    {
        key: '5',
        serialId: '#05',
        userName: 'Brooklyn Simmons',
        email: 'brooklyn@gmail.com',
        contactNumber: '(316) 555-0116',
        subscription: 'Monthly',
        status: 'active',
        country: 'Argentina',
        profession: 'Developer',
    },
    {
        key: '6',
        serialId: '#06',
        userName: 'Omar Yusuf',
        email: 'omar@gmail.com',
        contactNumber: '(406) 555-0120',
        subscription: 'Monthly',
        status: 'active',
        country: 'Japan',
        profession: 'Tester',
    },
    {
        key: '7',
        serialId: '#07',
        userName: 'Nikolai Ivanovich',
        email: 'nikolai@gmail.com',
        contactNumber: '(603) 555-0123',
        subscription: 'Yearly',
        status: 'delete',
        country: 'UK',
        profession: 'Cleaner',
    },
    {
        key: '8',
        serialId: '#08',
        userName: 'Brooklyn Simmons',
        email: 'brooklyn@gmail.com',
        contactNumber: '(316) 555-0116',
        subscription: 'Monthly',
        status: 'active',
        country: 'Brazil',
        profession: 'Football Player',
    },
    {
        key: '9',
        serialId: '#09',
        userName: 'Brooklyn Simmons',
        email: 'brooklyn@gmail.com',
        contactNumber: '(316) 555-0116',
        subscription: 'Monthly',
        status: 'active',
        country: 'Germany',
        profession: 'Manager',
    },
    {
        key: '10',
        serialId: '#10',
        userName: 'Brooklyn Simmons',
        email: 'brooklyn@gmail.com',
        contactNumber: '(316) 555-0116',
        subscription: 'Monthly',
        status: 'active',
        country: 'Turkey',
        profession: 'Ice cream seller',
    },
];
export interface User {
    key: string;
    serialId: string;
    userName: string;
    email: string;
    contactNumber: string;
    subscription: string;
    country: string;
    profession: string;
    status?: 'active' | 'delete';
}
